version: "3.8"
services:
  root:
    build:
      context: ./
      dockerfile: dockerfile
    image: senpai1996/root
    volumes:
      - ./:/Ekri/
    ports:
      - 2500:2500
  user:
    build:
      context: ./user-service
      dockerfile: ./dockerfile
    image: senpai1996/user
    restart: always
    volumes:
      - ./user-service:/Ekri/user-service
      - /user-service/node_modules
      - ./middelware/:/Ekri/middelware
      - ./models/:/Ekri/models
      - ./node_modules/:/Ekri/node_modules
      - ./package.json:/Ekri/package.json
    ports:
      - 2600:2600
  auth:
    build:
      context: ./auth-service
      dockerfile: dockerfile
    image: senpai1996/auth
    restart: always
    volumes:
      - ./auth-service:/Ekri/auth-service
      - /auth-service/node_modules
      - ./middelware/:/Ekri/middelware
      - ./models/:/Ekri/models
      - ./node_modules/:/Ekri/node_modules
      - ./package.json:/Ekri/package.json
    ports:
      - 2700:2700
  house:
    build:
      context: ./house-service
      dockerfile: dockerfile
    image: senpai1996/house
    restart: always
    volumes:
      - ./house-service:/Ekri/house-service
      - ./middelware/:/Ekri/middelware
      - ./models/:/Ekri/models
      - ./node_modules/:/Ekri/node_modules
      - ./package.json:/Ekri/package.json
    ports:
      - 2800:2800
  front:
    build:
      context: ./ekri-fe
      dockerfile: dockerfile
    image: senpai1996/front
    restart: always
    volumes:
      - ./ekri-fe:/Ekri/Ekri-FE
      - /Ekri/Ekri-FE/node_modules
    environment:
      - REACT_APP_URL=http://root:2500
    ports:
      - 3000:3000
volumes:
  dbdata6:
